### ISSUE TITLE
Ghostboard - Truncated AP Scan results

### ISSUE THREAD

**Issue by ProjectNemoSan** [jaylikesbunda/Ghost_ESP#216]
AP Scan does not list the first 10-25 APs. I've used the webUI to update and also uploaded .bins from here to see if it mattered, same issue. It was working fine before 1.9.0

**Comment by tototo31** [comment]
What setup are you using? Is it through the flipper app or the serial console?

**Comment by ProjectNemoSan** [comment]
Serial console,Ghostboard v1. And latest Momentum and Unleashed dev with your 1.6.1 firmware

**Comment by jaylikesbunda** [comment]
try 1.9, 1.6.1 is fairly old

**Comment by jaylikesbunda** [comment]
oh you're saying the app version 1.6.1 and firmware 1.9?

**Comment by jaylikesbunda** [comment]
@ProjectNemoSan this should be resolved on https://github.com/jaylikesbunda/Ghost_ESP/releases/tag/prerelease-20251225-030603-7f5eca9 my network isn't busy enough to actually cause the issue but i'm fairly sure i fixed it

**Comment by ProjectNemoSan** [comment]
I updated to latest stable as of last night (1.9.1) and the issues persists.
Thought id mention to that I keep getting the "Tip" notification popping up? It mentions the scan is paused and to hit right button to resume, i do and nothing is effected. Just curious as i don't remember that before.

**Comment by jaylikesbunda** [comment]
the scroll behaviour is intended it's so you can scroll up and not have the view jump to the bottom when more text comes in

**Comment by jaylikesbunda** [comment]
[ghost_esp.fap.renameme.txt](https://github.com/user-attachments/files/24343465/ghost_esp.fap.renameme.txt)

i've managed to nicely be able to fit at least 53 APs in the text area without being cutoff, i'd appreciate if you could test this when you have the time!

**Comment by ProjectNemoSan** [comment]
Tested it and it works, ran just an AP scan and then a AP and Station scan it both worked, viewed from the actual scan and then listed them. Ran them a few times with restarts so it works for me. Shouldn't be a problem setting view logs from the start? Appreciate it tons and Merry Christmas.
